### ISSUE TITLE
Redirect URL is incorrect on mailchimp

### ISSUE THREAD

**Issue by ryanlabouve** [OKCIndieHackers/okc-indie-hackers#6]
### Reproduction steps
* Fill out email, click submit
* On mailchimp page, click "continue to website"
* Incorrectly takes you to http://ockindiehackers.com/

*expected behavior* It takes you to http://okcindiehackers.com/

**Comment by ryanlabouve** [comment]
<img width="722" alt="okc indiehackers 2018-11-23 20-37-15" src="https://user-images.githubusercontent.com/1318878/48963772-9ffeaf00-ef5f-11e8-9d70-2c8031d3fdbd.png">

**Comment by matopher** [comment]
Fixed the URL in the list settings. This should resolve the issue.

Related note: It would be great to have a custom "Thank-you" page to redirect visitors after the form submission. This would allow us to easily track sign-up events and offer next steps to new subscribers.

We'd add it by creating the page, then adding the redirect URL to the Mailchimp form in List Settings.
