### ISSUE TITLE
Add CTA on our website for our first meetup

### ISSUE THREAD

**Issue by ryanlabouve** [OKCIndieHackers/okc-indie-hackers#8]
We've currently decided that our first meetup is Dec 13. <img width="832" alt="meetups for indie hackers 2018-11-23 21-00-31" src="https://user-images.githubusercontent.com/1318878/48963899-d5f16280-ef62-11e8-8f69-8de32924040c.png">

We should probably nail time a time/location and add deets fo the website

**Comment by matopher** [comment]
Handled by the new homepage PR.
